"""create_ai_cover_letters_table

Revision ID: 196aaef5a460
Revises: a8ce5399564d
Create Date: 2026-07-01 17:20:18.498271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '196aaef5a460'
down_revision: Union[str, None] = 'a8ce5399564d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cover_letters',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('writing_style', sa.String(length=50), nullable=False),
    sa.Column('generation_mode', sa.String(length=50), nullable=False),
    sa.Column('generated_content', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_cover_letters_resume_id'), 'ai_cover_letters', ['resume_id'], unique=False)
    op.create_index(op.f('ix_ai_cover_letters_user_id'), 'ai_cover_letters', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_cover_letters_user_id'), table_name='ai_cover_letters')
    op.drop_index(op.f('ix_ai_cover_letters_resume_id'), table_name='ai_cover_letters')
    op.drop_table('ai_cover_letters')
    # ### end Alembic commands ###
