"""create_ai_cover_letter_optimizations_table

Revision ID: 7dc39537251a
Revises: 196aaef5a460
Create Date: 2026-07-01 17:43:13.782163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dc39537251a'
down_revision: Union[str, None] = '196aaef5a460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cover_letter_optimizations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('cover_letter_id', sa.Uuid(), nullable=False),
    sa.Column('optimization_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('category_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keyword_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['ai_cover_letters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_cover_letter_optimizations_cover_letter_id'), 'ai_cover_letter_optimizations', ['cover_letter_id'], unique=False)
    op.create_index(op.f('ix_ai_cover_letter_optimizations_user_id'), 'ai_cover_letter_optimizations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_cover_letter_optimizations_user_id'), table_name='ai_cover_letter_optimizations')
    op.drop_index(op.f('ix_ai_cover_letter_optimizations_cover_letter_id'), table_name='ai_cover_letter_optimizations')
    op.drop_table('ai_cover_letter_optimizations')
    # ### end Alembic commands ###
