"""create_career_roadmap_tables

Revision ID: 95fe7c595d67
Revises: 8366d214bcff
Create Date: 2026-07-03 15:12:46.846564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95fe7c595d67'
down_revision: Union[str, None] = '8366d214bcff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_roadmaps',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=True),
    sa.Column('target_role', sa.String(length=100), nullable=False),
    sa.Column('current_role', sa.String(length=100), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=False),
    sa.Column('target_industry', sa.String(length=100), nullable=True),
    sa.Column('roadmap_status', sa.String(length=50), nullable=False),
    sa.Column('estimated_duration_months', sa.Integer(), nullable=False),
    sa.Column('current_readiness_score', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_roadmaps_resume_id'), 'career_roadmaps', ['resume_id'], unique=False)
    op.create_index(op.f('ix_career_roadmaps_user_id'), 'career_roadmaps', ['user_id'], unique=False)
    op.create_table('learning_recommendations',
    sa.Column('roadmap_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('resource_url', sa.String(length=500), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['career_roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_recommendations_roadmap_id'), 'learning_recommendations', ['roadmap_id'], unique=False)
    op.create_table('roadmap_milestones',
    sa.Column('roadmap_id', sa.Uuid(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['career_roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_milestones_roadmap_id'), 'roadmap_milestones', ['roadmap_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_milestones_roadmap_id'), table_name='roadmap_milestones')
    op.drop_table('roadmap_milestones')
    op.drop_index(op.f('ix_learning_recommendations_roadmap_id'), table_name='learning_recommendations')
    op.drop_table('learning_recommendations')
    op.drop_index(op.f('ix_career_roadmaps_user_id'), table_name='career_roadmaps')
    op.drop_index(op.f('ix_career_roadmaps_resume_id'), table_name='career_roadmaps')
    op.drop_table('career_roadmaps')
    # ### end Alembic commands ###
