"""add_profile_settings_and_notifications

Revision ID: d1aa056d44be
Revises: 95fe7c595d67
Create Date: 2026-07-05 17:59:39.979692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1aa056d44be'
down_revision: Union[str, None] = '95fe7c595d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=50), server_default=sa.text("'INFO'"), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('linkedin', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=100), server_default=sa.text("'Job Seeker'"), nullable=True))
    op.add_column('users', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('education', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('experience', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), server_default=sa.text("'UTC'"), nullable=False))
    op.add_column('users', sa.Column('theme', sa.String(length=20), server_default=sa.text("'dark'"), nullable=False))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('push_notifications', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('marketing_emails', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marketing_emails')
    op.drop_column('users', 'push_notifications')
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'theme')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'language')
    op.drop_column('users', 'experience')
    op.drop_column('users', 'education')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'role')
    op.drop_column('users', 'github')
    op.drop_column('users', 'linkedin')
    op.drop_column('users', 'website')
    op.drop_column('users', 'location')
    op.drop_column('users', 'bio')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
