"""add_has_onboarded_to_user

Revision ID: f36893c7d433
Revises: d1aa056d44be
Create Date: 2026-07-18 15:04:31.141145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36893c7d433'
down_revision: Union[str, None] = 'd1aa056d44be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_onboarded', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_onboarded')
    # ### end Alembic commands ###
