import React from 'react'
import { motion } from 'framer-motion'
import { Award, CheckCircle2, AlertTriangle, MessageSquare, Zap, Target, Sparkles } from 'lucide-react'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/Card'
import type { AIFeedbackBreakdown } from '@/types/interviewPrep'

export interface FeedbackPanelProps {
  feedback: AIFeedbackBreakdown | null
}

export function FeedbackPanel({ feedback }: FeedbackPanelProps) {
  if (!feedback) return null

  const scores = [
    { label: 'Communication Delivery', value: feedback.communicationScore, icon: MessageSquare },
    { label: 'Technical Accuracy', value: feedback.technicalAccuracyScore, icon: Zap },
    { label: 'Problem Solving Depth', value: feedback.problemSolvingScore, icon: Target },
    { label: 'Confidence & Assuredness', value: feedback.confidenceScore, icon: Sparkles },
    { label: 'Clarity & Articulation', value: feedback.clarityScore, icon: MessageSquare },
    { label: 'STAR Methodology Structure', value: feedback.starStructureScore, icon: Award },
  ]

  return (
    <Card className="bg-[#10121e]/90 border border-white/10 rounded-2xl p-5 hover:border-purple-500/30 transition-all space-y-4 text-left">
      <CardHeader className="p-0 pb-3 flex flex-row items-center justify-between border-b border-white/10">
        <div className="flex items-center gap-2">
          <div className="p-2 rounded-xl bg-purple-500/20 text-purple-400">
            <Award className="h-5 w-5" />
          </div>
          <div>
            <CardTitle className="text-base font-bold text-white">
              AI Evaluation & Criteria Feedback
            </CardTitle>
            <p className="text-xs text-slate-400 font-medium mt-0.5">
              Comprehensive analysis generated by Scorelia AI Career Engine
            </p>
          </div>
        </div>

        <div className="flex items-center gap-1.5 px-3 py-1 rounded-xl bg-emerald-500/15 border border-emerald-500/30">
          <span className="text-xs font-bold text-slate-300">Overall Rating:</span>
          <span className="text-sm font-black text-emerald-400 font-mono">
            {feedback.overallRatingPercent}%
          </span>
        </div>
      </CardHeader>

      <CardContent className="p-0 space-y-4 text-xs">
        {/* Strengths & Weaknesses */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
          {/* Strengths */}
          <div className="p-3.5 rounded-xl bg-emerald-950/20 border border-emerald-500/20 space-y-2">
            <span className="text-xs font-bold text-emerald-400 flex items-center gap-1.5">
              <CheckCircle2 className="h-4 w-4 text-emerald-400" /> Key Strengths Identified
            </span>
            <ul className="space-y-1.5 pl-4 list-disc text-slate-300 font-medium">
              {feedback.strengths.map((str, i) => (
                <li key={i} className="leading-relaxed">{str}</li>
              ))}
            </ul>
          </div>

          {/* Areas to Improve */}
          <div className="p-3.5 rounded-xl bg-amber-950/20 border border-amber-500/20 space-y-2">
            <span className="text-xs font-bold text-amber-400 flex items-center gap-1.5">
              <AlertTriangle className="h-4 w-4 text-amber-400" /> Actionable Improvements
            </span>
            <ul className="space-y-1.5 pl-4 list-disc text-slate-300 font-medium">
              {feedback.areasToImprove.map((area, i) => (
                <li key={i} className="leading-relaxed">{area}</li>
              ))}
            </ul>
          </div>
        </div>

        {/* Detailed Criteria Scores */}
        <div className="space-y-2.5 pt-2 border-t border-white/5">
          <span className="text-xs font-bold text-white block">
            Detailed Performance Metrics Breakdown
          </span>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {scores.map((s, i) => {
              const Icon = s.icon
              return (
                <div key={i} className="p-2.5 rounded-xl bg-[#141627] border border-white/5 space-y-1">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-1.5 text-slate-300 font-medium truncate">
                      <Icon className="h-3.5 w-3.5 text-purple-400 shrink-0" />
                      <span className="truncate">{s.label}</span>
                    </div>
                    <span className="font-bold text-white font-mono shrink-0 ml-2">{s.value}%</span>
                  </div>
                  <div className="h-1.5 w-full bg-white/5 rounded-full overflow-hidden">
                    <motion.div
                      initial={{ width: 0 }}
                      animate={{ width: `${s.value}%` }}
                      transition={{ duration: 0.5, delay: i * 0.05 }}
                      className="h-full bg-gradient-to-r from-purple-500 to-emerald-500 rounded-full"
                    />
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
export default FeedbackPanel
